// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using caothang.Data;

namespace caothang.Migrations
{
    [DbContext(typeof(DPContext))]
    [Migration("20210710080954_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("caothang.Areas.Admin.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PlayStaion 4",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Xbox One S",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nintendo Switch",
                            Status = true
                        });
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.GalleryImageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("productsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productsId");

                    b.ToTable("galleryImages");
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.InvoiceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.Invoice_DetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("invoiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.HasIndex("invoiceId");

                    b.ToTable("invoice_Details");
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desciption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 797, DateTimeKind.Local).AddTicks(9236),
                            Desciption = "Đẹp",
                            Image = "Máy PS4 Pro The Last Of Us 2 Limited Edition.jpg",
                            Name = "Máy PS4 Pro The Last Of Us 2 Limited Edition",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(140),
                            Desciption = "Đẹp",
                            Image = "Máy PS4 Slim 1TB.jpg",
                            Name = "Máy PS4 Slim 1TB",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(188),
                            Desciption = "Đẹp",
                            Image = "Máy PS4 Pro The Last Of Us 2 Limited Edition.jpg",
                            Name = "Sony PS4 Slim Days Of Play 2019 Limited Edition",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(191),
                            Desciption = "Đẹp",
                            Image = "PS4 Pro 2nd hand.jpg",
                            Name = "PS4 Pro 2nd hand",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(193),
                            Desciption = "Đẹp",
                            Image = "PS4 Pro 2nd hand.jpg",
                            Name = "Xbox Series X",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(195),
                            Desciption = "Đẹp",
                            Image = "Xbox Series X.jpg",
                            Name = "Xbox Series X",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(197),
                            Desciption = "Đẹp",
                            Image = "Xbox Series X.jpg",
                            Name = "Xbox Series X",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(199),
                            Desciption = "Đẹp",
                            Image = "Xbox Series S.jpg",
                            Name = "Xbox Series S",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(202),
                            Desciption = "Đẹp",
                            Image = "Máy Nintendo Switch V2 Màu Neon.jpg",
                            Name = "Máy Nintendo Switch V2 Màu Neon",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(205),
                            Desciption = "Đẹp",
                            Image = "Máy Nintendo Switch Lite - Màu Blue.jpg",
                            Name = "Máy Nintendo Switch Lite - Màu Blue",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(207),
                            Desciption = "Đẹp",
                            Image = "Máy Nintendo Switch Fortnite Special Edition.jpg",
                            Name = "Máy Nintendo Switch Fortnite Special Edition",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(209),
                            Desciption = "Đẹp",
                            Image = "Máy Nintendo Switch Animal Crossing.jpg",
                            Name = "Máy Nintendo Switch Animal Crossing",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        });
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.Product_DetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("productsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productsId");

                    b.ToTable("product_Details");
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.RolesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            Status = true
                        });
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avarta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "115 Trần Xuân Soạn",
                            Avarta = "user-1.png",
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(7166),
                            Email = "duyvo049@gmail.com",
                            FullName = "Võ Thành Duy",
                            PassWord = "25f9e794323b453885f5181f1b624d0b",
                            Phone = "0393030574",
                            RolesId = 1,
                            Status = true,
                            UserName = "thanhduy"
                        },
                        new
                        {
                            Id = 2,
                            Address = "115 Trần Xuân Soạn",
                            Avarta = "user-2.png",
                            CreatedOn = new DateTime(2021, 7, 10, 15, 9, 53, 799, DateTimeKind.Local).AddTicks(8316),
                            Email = "leloc603@gmail.com",
                            FullName = "Lê Xuân Lộc",
                            PassWord = "25f9e794323b453885f5181f1b624d0b",
                            Phone = "0393030574",
                            RolesId = 2,
                            Status = true,
                            UserName = "leloc"
                        });
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.GalleryImageModel", b =>
                {
                    b.HasOne("caothang.Areas.Admin.Models.ProductModel", "products")
                        .WithMany("GalleryImage")
                        .HasForeignKey("productsId");
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.Invoice_DetailsModel", b =>
                {
                    b.HasOne("caothang.Areas.Admin.Models.ProductModel", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("caothang.Areas.Admin.Models.UserModel", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("caothang.Areas.Admin.Models.InvoiceModel", "invoice")
                        .WithMany("invoice_Details")
                        .HasForeignKey("invoiceId");
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.ProductModel", b =>
                {
                    b.HasOne("caothang.Areas.Admin.Models.CategoryModel", "category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.Product_DetailsModel", b =>
                {
                    b.HasOne("caothang.Areas.Admin.Models.ProductModel", "products")
                        .WithMany("product_detail")
                        .HasForeignKey("productsId");
                });

            modelBuilder.Entity("caothang.Areas.Admin.Models.UserModel", b =>
                {
                    b.HasOne("caothang.Areas.Admin.Models.RolesModel", "roles")
                        .WithMany("user")
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
