// <auto-generated />
using System;
using Common.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Project.Migrations
{
    [DbContext(typeof(DPContext))]
    [Migration("20210720135300_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Areas.Admin.Models.CategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PlayStaion 4",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "Xbox One S",
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nintendo Switch",
                            Status = true
                        });
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.InvoiceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductModelId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductModelId");

                    b.HasIndex("UserId");

                    b.ToTable("invoice");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Invoice_DetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ProductId");

                    b.ToTable("invoice_Details");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desciption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 235, DateTimeKind.Local).AddTicks(2939),
                            Desciption = "Đẹp",
                            Image = "Máy PS4 Pro The Last Of Us 2 Limited Edition.jpg",
                            Name = "PS4 Pro The Last Of Us 2 Limited Edition",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(588),
                            Desciption = "Đẹp",
                            Image = "Máy PS4 Slim 1TB.jpg",
                            Name = "PS4 Slim 1TB",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(645),
                            Desciption = "Đẹp",
                            Image = "Máy PS4 Pro The Last Of Us 2 Limited Edition.jpg",
                            Name = "Sony PS4 Slim Days Of Play 2019 Limited Edition",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(654),
                            Desciption = "Đẹp",
                            Image = "PS4 Pro 2nd hand.jpg",
                            Name = "PS4 Pro 2nd hand",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(658),
                            Desciption = "Đẹp",
                            Image = "PS4 Pro 2nd hand.jpg",
                            Name = "Xbox Series X",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(663),
                            Desciption = "Đẹp",
                            Image = "Xbox Series X.jpg",
                            Name = "Xbox Series X",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(668),
                            Desciption = "Đẹp",
                            Image = "Xbox Series X.jpg",
                            Name = "Xbox Series X",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(673),
                            Desciption = "Đẹp",
                            Image = "Xbox Series S.jpg",
                            Name = "Xbox Series S",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(678),
                            Desciption = "Đẹp",
                            Image = "Máy Nintendo Switch V2 Màu Neon.jpg",
                            Name = "Nintendo Switch V2 Màu Neon",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(683),
                            Desciption = "Đẹp",
                            Image = "Máy Nintendo Switch Lite - Màu Blue.jpg",
                            Name = "Nintendo Switch Lite - Màu Blue",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(687),
                            Desciption = "Đẹp",
                            Image = "Máy Nintendo Switch Fortnite Special Edition.jpg",
                            Name = "Nintendo Switch Fortnite Special Edition",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 237, DateTimeKind.Local).AddTicks(693),
                            Desciption = "Đẹp",
                            Image = "Máy Nintendo Switch Animal Crossing.jpg",
                            Name = "Nintendo Switch Animal Crossing",
                            Price = 299m,
                            Quantity = 50,
                            Status = true
                        });
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Product_DetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GPU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("productsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("productsId");

                    b.ToTable("product_Details");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.RolesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Name = "User",
                            Status = true
                        });
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avarta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolesId");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "115 Trần Xuân Soạn",
                            Avarta = "user-1.png",
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 238, DateTimeKind.Local).AddTicks(507),
                            Email = "duyvo049@gmail.com",
                            FullName = "Võ Thành Duy",
                            PassWord = "25f9e794323b453885f5181f1b624d0b",
                            Phone = "0393030574",
                            RolesId = 1,
                            Status = true,
                            UserName = "thanhduy"
                        },
                        new
                        {
                            Id = 2,
                            Address = "115 Trần Xuân Soạn",
                            Avarta = "user-2.png",
                            CreatedOn = new DateTime(2021, 7, 20, 20, 52, 59, 238, DateTimeKind.Local).AddTicks(2225),
                            Email = "leloc603@gmail.com",
                            FullName = "Lê Xuân Lộc",
                            PassWord = "25f9e794323b453885f5181f1b624d0b",
                            Phone = "0393030574",
                            RolesId = 2,
                            Status = true,
                            UserName = "leloc"
                        });
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.InvoiceModel", b =>
                {
                    b.HasOne("Project.Areas.Admin.Models.ProductModel", null)
                        .WithMany("invoices")
                        .HasForeignKey("ProductModelId");

                    b.HasOne("Project.Areas.Admin.Models.UserModel", "user")
                        .WithMany("invoices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Invoice_DetailsModel", b =>
                {
                    b.HasOne("Project.Areas.Admin.Models.InvoiceModel", "invoice")
                        .WithMany("invoice_Details")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Areas.Admin.Models.ProductModel", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("invoice");

                    b.Navigation("product");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.ProductModel", b =>
                {
                    b.HasOne("Project.Areas.Admin.Models.CategoryModel", "category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.Product_DetailsModel", b =>
                {
                    b.HasOne("Project.Areas.Admin.Models.ProductModel", "products")
                        .WithMany("product_detail")
                        .HasForeignKey("productsId");

                    b.Navigation("products");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.UserModel", b =>
                {
                    b.HasOne("Project.Areas.Admin.Models.RolesModel", "roles")
                        .WithMany("user")
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("roles");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.CategoryModel", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.InvoiceModel", b =>
                {
                    b.Navigation("invoice_Details");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.ProductModel", b =>
                {
                    b.Navigation("invoices");

                    b.Navigation("product_detail");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.RolesModel", b =>
                {
                    b.Navigation("user");
                });

            modelBuilder.Entity("Project.Areas.Admin.Models.UserModel", b =>
                {
                    b.Navigation("invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
